# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='joined_users',
            field=models.ManyToManyField(to='TravelBuddy.User'),
        ),
    ]
